name: Copy Dashboards
on:
  repository_dispatch:
    types:
      - webhook
jobs:
  copy-dashboards:
    runs-on: ubuntu-latest
    steps:
      - run: echo "webhook triggered"
      - run: 'echo "field: ${{ github.event.client_payload.name }}"'
  sparse-checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: snow-actions/sparse-checkout@v1.1.0
        with:
          patterns: .github
          repository: jadensy/actions_test_source
          token: ${{ secrets.WF_PAT }}
          path: ./copied_dashboards