name: Copy Dashboards
on:
  repository_dispatch:
    types:
      - webhook
jobs:
  copy-dashboards:
    runs-on: ubuntu-latest
    steps:
      - run: echo "webhook triggered"
      - run: 'echo "field: ${{ github.event.client_payload.name }}"'
